BEGIN;

INSERT INTO sc_auditoria.tb_catalogo_dados
(esquema_nome, tabela_nome, coluna_nome, descricao, regra_negocio_critica, nivel_acesso_leitura, nivel_acesso_escrita)
VALUES
-- ==============================================================================
-- SCHEMA: sc_auditoria (Governança e Metadados)
-- ==============================================================================
('sc_auditoria', 'tb_catalogo_dados', 'id', 'Identificador único do registro no catálogo de dados.',
 'Chave primária do catálogo.', 'auditoria', 'administrativo'),
('sc_auditoria', 'tb_catalogo_dados', 'esquema_nome', 'Nome do schema no PostgreSQL.', 'Organização física do banco.',
 'auditoria', 'administrativo'),
('sc_auditoria', 'tb_catalogo_dados', 'tabela_nome', 'Nome da tabela catalogada.', 'Mapeamento estrutural.',
 'auditoria', 'administrativo'),
('sc_auditoria', 'tb_catalogo_dados', 'coluna_nome', 'Nome da coluna física da tabela.', 'Mapeamento estrutural.',
 'auditoria', 'administrativo'),
('sc_auditoria', 'tb_catalogo_dados', 'descricao', 'Definição e contexto de uso do campo.',
 'Documentação ativa obrigatória.', 'auditoria', 'administrativo'),
('sc_auditoria', 'tb_catalogo_dados', 'regra_negocio_critica', 'Restrições operacionais vinculadas (ex: bloqueios).',
 'Base para auditoria de negócio.', 'auditoria', 'administrativo'),
('sc_auditoria', 'tb_catalogo_dados', 'nivel_acesso_leitura', 'Nível mínimo para visualizar este dado.',
 'Segurança e LGPD.', 'auditoria', 'administrativo'),
('sc_auditoria', 'tb_catalogo_dados', 'nivel_acesso_escrita', 'Nível mínimo para alterar este dado.',
 'Segurança e LGPD.', 'auditoria', 'administrativo'),
('sc_auditoria', 'tb_catalogo_dados', 'atualizado_em', 'Timestamp da última atualização do metadado.',
 'Auditoria da documentação.', 'auditoria', 'administrativo'),

('sc_auditoria', 'tb_auditoria_log', 'id', 'Identificador do log transacional.', 'Chave primária do log imutável.',
 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_auditoria_log', 'empresa_id', 'Referência ao tenant logado (opcional caso seja global).',
 'Isolamento de acesso do log.', 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_auditoria_log', 'tabela_afetada', 'Tabela de origem da modificação.', 'Rastreabilidade DML.',
 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_auditoria_log', 'operacao', 'INSERT, UPDATE ou DELETE.', 'Rastreabilidade de comportamento.',
 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_auditoria_log', 'usuario_db', 'Usuário do PostgreSQL que executou a ação.',
 'Rastreabilidade de infraestrutura.', 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_auditoria_log', 'dados_antigos', 'Estado do registro (JSONB) antes da alteração (OLD).',
 'Reversão / Auditoria de fraude.', 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_auditoria_log', 'dados_novos', 'Estado do registro (JSONB) após a alteração (NEW).',
 'Rastreabilidade final.', 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_auditoria_log', 'data_hora', 'Carimbo de tempo exato da transação.',
 'Imutável e gerado via trigger.', 'auditoria', 'auditoria'),

('sc_auditoria', 'tb_monitoramento_dau', 'id', 'Identificador do acesso (Daily Active Users).',
 'Chave primária do DAU.', 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_monitoramento_dau', 'usuario_id', 'Referência ao usuário logado no aplicativo.',
 'Vinculado a tb_usuario.', 'auditoria', 'auditoria'),
('sc_auditoria', 'tb_monitoramento_dau', 'data_acesso', 'Data do acesso contada uma vez por dia.',
 'Unique com usuario_id.', 'auditoria', 'auditoria'),


-- ==============================================================================
-- SCHEMA: sc_corporativo (Organização e Parâmetros)
-- ==============================================================================
('sc_corporativo', 'tb_endereco', 'id', 'Identificador único do endereço.', 'Chave primária de endereço.', 'conducao',
 'administrativo'),
('sc_corporativo', 'tb_endereco', 'cep', 'Código Postal da localidade.', 'Garante precisão logística.', 'conducao',
 'administrativo'),
('sc_corporativo', 'tb_endereco', 'logradouro', 'Rua, rodovia, estrada ou via da localidade.',
 'Necessário para GPS/Roteirização.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_endereco', 'numero', 'Número ou Km (em caso de rodovia).', 'Necessário para GPS/Roteirização.',
 'conducao', 'administrativo'),
('sc_corporativo', 'tb_endereco', 'cidade', 'Município do logradouro.', 'Necessário para GTA e emissão fiscal.',
 'conducao', 'administrativo'),
('sc_corporativo', 'tb_endereco', 'estado', 'UF do município (Sigla).', 'Necessário para GTA e barreiras fiscais.',
 'conducao', 'administrativo'),

('sc_corporativo', 'tb_empresa', 'id', 'Identificador matriz/tenant (Ex: JBS).', 'Isolamento base (Multitenancy).',
 'conducao', 'administrativo'),
('sc_corporativo', 'tb_empresa', 'endereco_id', 'Referência à sede corporativa.', 'Obrigatório endereço.', 'conducao',
 'administrativo'),
('sc_corporativo', 'tb_empresa', 'nome', 'Nome Fantasia da empresa de logística/frigorífico.',
 'Uso em UI e relatórios.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_empresa', 'razao_social', 'Nome Legal da empresa.', 'Vinculado ao faturamento.', 'conducao',
 'administrativo'),
('sc_corporativo', 'tb_empresa', 'codigo_interno', 'Código de integração SAP/ERP interno.',
 'Integração de dados corporativos.', 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_empresa', 'email', 'E-mail principal corporativo.', 'Meio oficial de comunicação.', 'conducao',
 'administrativo'),
('sc_corporativo', 'tb_empresa', 'cnpj', 'CNPJ com formatação/sem formatação.',
 'Único no banco de dados. Validation fiscal.', 'conducao', 'administrativo'),

('sc_corporativo', 'tb_configuracao_operacao', 'id', 'Identificador dos parâmetros.', 'Um por empresa.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'empresa_id', 'Referência à empresa dos parâmetros.',
 'Restrição UNIQUE.', 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'tempo_max_viagem_horas',
 'Alerta para limite de bem-estar animal em trânsito.', 'Viagens longas afetam pH da carne e bem-estar.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'mortalidade_bloqueio_cabecas',
 'Quantidade que bloqueia viagem (gatilho emergencial).', 'Ex: +1 morto retém aprovação automática.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'prazo_analise_horas', 'SLA da auditoria para fechar diário.',
 'Monitoramento de eficiência de equipe.', 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'meta_mortalidade', 'Limite percentual tolerável de mortes/mês.',
 'Métrica crítica ESG e Qualidade.', 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'qtd_assinaturas_obrigatorias',
 'Número de assinaturas requeridas para liberar GTA.', 'Trava de envio do formulário Mobile.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'alerta_sirene_re', 'Avisar corporativo se a sirene não funcionou.',
 'Checklist de segurança (SESMT).', 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'alerta_inspecao_dias',
 'Quantos dias antes do vencimento notificar frota.', 'Evitar caminhão apreendido na barreira.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'alerta_cnh_vencida', 'Bloquear/Avisar motorista com CNH irregular.',
 'Trigger de segurança trava a alocação.', 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'alerta_tempo_parada_imprevista',
 'Minutos de parada que acionam alerta na matriz.', 'Combate a furtos de carga e sinistro.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_configuracao_operacao', 'atualizado_em', 'Data da última alteração de parâmetros.',
 'Log de gestão.', 'auditoria', 'administrativo'),

('sc_corporativo', 'tb_usuario', 'id', 'Identificador (colaboradores/externos).',
 'Chave de relacionamentos do usuário.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'empresa_id', 'Referência ao tenant.', 'Pertencimento.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'tipo', 'Motorista, Analista, Pecuarista, etc.', 'Define perfil de tela no App/Web.',
 'conducao', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'cargo', 'Nomenclatura RH do cargo.', 'Informacional.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'nivel_acesso', 'Hierarquia de permissões no sistema.', 'RBAC do aplicativo.',
 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'cpf', 'CPF (Documento Único).', 'Único, obrigatório. Dado PII (Sensível).',
 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'cnh_numero', 'Nº de Registro da CNH.', 'Obrigatório para Motoristas e Manobristas.',
 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'categoria_cnh', 'A, B, C, D, E.', 'Motorista precisa ser E para carreta.',
 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'data_vencimento_cnh', 'Vencimento para bloqueio de alocação.',
 'Regra impeditiva em triggers.', 'auditoria', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'nome_completo', 'Nome civil do usuário.', 'Impressão nas assinaturas e relatórios.',
 'conducao', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'data_nascimento', 'Data nascimento (PII).', 'Validação secundária.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_usuario', 'email', 'Login e comunicação.', 'Dado PII (Sensível). Unique.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_usuario', 'telefone', 'Contato emergencial / WhatsApp.', 'Telemetria e despacho.', 'auditoria',
 'administrativo'),
('sc_corporativo', 'tb_usuario', 'senha_hash', 'Hash criptográfico (bcrypt/pgcrypto).', 'Nunca trafegar em plain-text.',
 'administrativo', 'administrativo'),
('sc_corporativo', 'tb_usuario', 'url_assinatura_geral', 'Link para imagem da assinatura pré-cadastrada.',
 'Evita o motorista assinar 100x na tela do tablet.', 'conducao', 'conducao'),
('sc_corporativo', 'tb_usuario', 'status_cadastro', 'Ativo ou inativo.', 'Bloqueio instantâneo de login.', 'conducao',
 'administrativo'),

('sc_corporativo', 'tb_fazenda', 'id', 'Identificador de origem.', 'Chave de embarque.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_fazenda', 'empresa_id', 'Referência ao tenant.', 'Pertencimento.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_fazenda', 'pecuarista_id', 'Responsável civil pela fazenda.',
 'Necessário para vínculo de assinatura do proprietário.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_fazenda', 'endereco_id', 'Localização física do embarcadouro.', 'Logística de chegada.',
 'conducao', 'administrativo'),
('sc_corporativo', 'tb_fazenda', 'nome', 'Nome comum da propriedade.', 'Impressão em relatórios JBS.', 'conducao',
 'administrativo'),
('sc_corporativo', 'tb_fazenda', 'razao_social', 'Nome legal caso seja PJ.', 'Fiscal.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_fazenda', 'cnpj', 'CNPJ da propriedade rural.', 'Cadastro Fiscal.', 'conducao',
 'administrativo'),

('sc_corporativo', 'tb_unidade_frigorifica', 'id', 'Identificador de destino (frigorífico).', 'Chave de desembarque.',
 'conducao', 'administrativo'),
('sc_corporativo', 'tb_unidade_frigorifica', 'empresa_id', 'Referência ao tenant.', 'Pertencimento.', 'conducao',
 'administrativo'),
('sc_corporativo', 'tb_unidade_frigorifica', 'analista_id', 'Auditor/Auditora responsável da planta.',
 'Encaminhamento no fluxo de aprovação.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_unidade_frigorifica', 'endereco_id', 'Localização física do desembarcadouro.',
 'Logística de destino.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_unidade_frigorifica', 'nome', 'Planta ou Unidade (Ex: Unidade Lins).',
 'Identificação gerencial.', 'conducao', 'administrativo'),
('sc_corporativo', 'tb_unidade_frigorifica', 'cnpj', 'CNPJ do Frigorífico.', 'Obrigatório (Único). Fiscal GTA.',
 'conducao', 'administrativo'),
('sc_corporativo', 'tb_unidade_frigorifica', 'qtd_currais', 'Número máximo de currais de espera.',
 'Validação do N° do curral apontado pelo motorista.', 'conducao', 'administrativo'),


-- ==============================================================================
-- SCHEMA: sc_frota (Composição Logística)
-- ==============================================================================
('sc_frota', 'tb_veiculo_base', 'id', 'ID da placa genérica.', 'Herança do PostgreSQL.', 'conducao', 'administrativo'),
('sc_frota', 'tb_veiculo_base', 'empresa_id', 'Tenant.', 'Isolamento.', 'conducao', 'administrativo'),
('sc_frota', 'tb_veiculo_base', 'placa', 'Mercosul/Padrão Antigo.', 'Único.', 'conducao', 'administrativo'),
('sc_frota', 'tb_veiculo_base', 'ativo', 'Status do veículo (oficina/inativo).', 'Impede seleção no App.', 'conducao',
 'administrativo'),
('sc_frota', 'tb_veiculo_base', 'data_vencimento_inspecao', 'Validade sanitária e mecânica.',
 'Bloqueia alocação se vencida via Trigger.', 'conducao', 'administrativo'),

('sc_frota', 'tb_veiculo_cavalo', 'km_acumulado', 'Odômetro atual do caminhão trator.',
 'Cálculo de depreciação e manutenção preventiva.', 'conducao', 'administrativo'),
('sc_frota', 'tb_veiculo_carreta', 'capacidade_cabecas', 'Capacidade de gado calculada do reboque.',
 'Valida superlotação/quebra de densidade.', 'conducao', 'administrativo'),


-- ==============================================================================
-- SCHEMA: sc_operacao (Relatório de Viagem)
-- ==============================================================================
('sc_operacao', 'tb_dominio_motivo_parada', 'id', 'ID do domínio de parada.', 'Lookup dinâmico.', 'conducao',
 'administrativo'),
('sc_operacao', 'tb_dominio_motivo_parada', 'codigo', 'Problema mecânico, Transbordo, Acidente...',
 'Mapeamento das caixas de seleção da JBS.', 'conducao', 'administrativo'),
('sc_operacao', 'tb_dominio_motivo_parada', 'descricao', 'Texto visível no App.', 'Legibilidade.', 'conducao',
 'administrativo'),
('sc_operacao', 'tb_dominio_motivo_parada', 'ativo', 'Status de uso.', 'Soft delete de opções.', 'conducao',
 'administrativo'),

('sc_operacao', 'tb_dominio_anomalia', 'id', 'ID da anomalia.', 'Lookup dinâmico.', 'conducao', 'administrativo'),
('sc_operacao', 'tb_dominio_anomalia', 'tipo_etapa', 'EMBARQUE ou DESEMBARQUE.',
 'Filtra os checklists corretos na tela Mobile.', 'conducao', 'administrativo'),
('sc_operacao', 'tb_dominio_anomalia', 'codigo', 'Ex: Gaiola com buraco, Animal mancando...',
 'Mapeia os checklists (quadradinhos) da ficha de papel.', 'conducao', 'administrativo'),
('sc_operacao', 'tb_dominio_anomalia', 'descricao', 'Texto visível no App.', 'Legibilidade.', 'conducao',
 'administrativo'),
('sc_operacao', 'tb_dominio_anomalia', 'ativo', 'Status de uso.', 'Soft delete de opções.', 'conducao',
 'administrativo'),


-- NÚCLEO DO RELATÓRIO
('sc_operacao', 'tb_relatorio_viagem', 'id', 'ID Transacional do documento impresso (JBS).',
 'Chave Primária e vínculo de BI.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'empresa_id', 'Referência ao tenant.', 'Garante isolamento.', 'conducao',
 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'status', 'Rascunho, Pendente (enviado), Aprovado, Reprovado.',
 'Trava envio repetido e dita fluxo do Analista.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'fazenda_id', 'Origem (Nome pecuarista/propriedade).',
 'Início da rota (Geoloc).', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'motorista_id', 'Código/Motorista (Campo Cabeçalho).', 'Identificação direta.',
 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'manobrista_id', 'Responsável pela manobra do veículo (se houver).',
 'Necessário para a segunda assinatura.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'curraleiro_id', 'Recebedor responsável na planta frigorífica.',
 'Responsável pela última assinatura (aceite).', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'cavalo_id', 'Placa do caminhão (cavalo).', 'Cabeçalho do formulário JBS.',
 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'carreta_id', 'Placa do reboque (carreta).', 'Cabeçalho do formulário JBS.',
 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'numero_gta', 'Nº da Guia de Trânsito Animal.',
 'Obrigatório (ÚNICO). Impede viagem fria.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'numero_nota_fiscal', 'Nº Nota fiscal do transporte.', 'Faturamento/Frete.',
 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'capacidade_carga_utilizada', 'Métrica de aproveitamento do deck/gaiola.',
 'Avaliar frete morto vs superlotação.', 'conducao', 'conducao'),

-- Datas de Embarque
('sc_operacao', 'tb_relatorio_viagem', 'data_embarque', 'Data de carregamento (Papel: Data embarque).',
 'Sincronia cronológica.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'horario_embarque', 'Horário de embarque (Papel: Horário embarque).',
 'Gestão de carga horária (CLT).', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'horario_saida_propriedade',
 'Momento que o veículo parte (Papel: Horário de saída).', 'Tempo real de trânsito vs repouso.', 'conducao',
 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'km_saida_embarcadouro',
 'Odômetro na fazenda (Papel: Km saída do embarcadouro).', 'Prevenção de desvio de rota.', 'conducao', 'conducao'),

-- Datas de Desembarque
('sc_operacao', 'tb_relatorio_viagem', 'data_chegada_unidade', 'Data de chegada no frigorífico.',
 'Sincronia cronológica de destino.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'horario_chegada_unidade',
 'Chegada portaria (Papel: Horário chegada na unidade).', 'Tempo de espera (Fila) na planta.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'horario_desembarque', 'Gado descarregado (Papel: Horário do desembarque).',
 'Tempo final com carga viva.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'km_chegada_desembarcadouro', 'Odômetro na planta (Papel: Km chegada...).',
 'Cálculo km rodado vs telemetria.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'numero_curral', 'Nº do curral onde o lote foi colocado (Papel: Nº curral).',
 'Rastreabilidade de abate.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'sirene_re_funcionou',
 'Checkbox segurança SESMT (Papel: A sirene de ré... funcionou?).', 'Gatilho de alerta corporativo e oficina.',
 'conducao', 'conducao'),

-- Contagens Embarque
('sc_operacao', 'tb_relatorio_viagem', 'qtd_machos', 'N° Machos embarcados.',
 'Prevenção de troca de sexo de boi de reposição.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'qtd_femeas', 'N° Fêmeas embarcadas.', 'Identificação de lote.', 'conducao',
 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'qtd_marrucos', 'Boi inteiro brigador (Papel: Marrucos).',
 'Requer separação, causa mortes no trânsito se misturado.', 'conducao', 'conducao'),

-- Contagens Desembarque
('sc_operacao', 'tb_relatorio_viagem', 'qtd_em_pe', 'Gado entregue íntegro (Papel: Em pé).', 'Performance padrão.',
 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'qtd_deitado', 'Gado fadigado/pisoteado mas vivo (Papel: Deitado).',
 'Indicador de falha no transporte ou estrada ruim.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'qtd_morto', 'Gado sem vida (Papel: Morto).',
 'Impacto financeiro, gera notificação para SIF (Serviço Inspecao Federal).', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'qtd_emergencia', 'Abate emergencial obrigatório (Papel: Emergência).',
 'Perda parcial da carcaça, exige SIF imediato.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'url_laudo_mortalidade',
 'Imagem/Link de evidência (Ex: Foto da orelha ou laudo).', 'Auditoria de veracidade em caso de perda patrimonial.',
 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'motivo_emergencia', 'Texto explicativo do motorista/veterinário.',
 'Exigido se qtd_emergencia > 0.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'comentarios', 'Campo de anotação livre do relatório (Papel: Comentários).',
 'Contexto extra da viagem.', 'conducao', 'conducao'),

-- Bloco de Assinaturas
('sc_operacao', 'tb_relatorio_viagem', 'url_assinatura_pecuarista',
 'Assinatura (Upload/Canvas) (Papel: Assinatura resp. fazenda).', 'Termo de Aceite Fiscal (Transferência Posse).',
 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'url_assinatura_motorista',
 'Assinatura (Upload/Canvas) (Papel: Assinatura entregador motorista).',
 'Assunção de responsabilidade pela carga/caminhão.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'url_assinatura_manobrista',
 'Assinatura (Upload/Canvas) (Papel: Assinatura entregador manobrista).',
 'Check-in do equipamento no pátio frigorífico.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'url_assinatura_curraleiro',
 'Assinatura (Upload/Canvas) (Papel: Assinatura recebedor curraleiro).',
 'Recibo oficial da planta. Carga entra para o abate.', 'conducao', 'conducao'),

('sc_operacao', 'tb_relatorio_viagem', 'criado_em', 'Momento (TIMESTAMP) de abertura do rascunho.',
 'Registro sistêmico.', 'conducao', 'conducao'),
('sc_operacao', 'tb_relatorio_viagem', 'enviado_em', 'Momento do clique de (Sincronizar).',
 'Cálculo de conexão Offline/Online.', 'conducao', 'conducao'),


-- Sub-tabelas N:N do Relatório
('sc_operacao', 'tb_parada_imprevista', 'id', 'ID da parada no banco.', 'Chave primária.', 'conducao', 'conducao'),
('sc_operacao', 'tb_parada_imprevista', 'relatorio_id', 'Referência à viagem.', 'Foreign Key obrigatória.', 'conducao',
 'conducao'),
('sc_operacao', 'tb_parada_imprevista', 'dominio_parada_id', 'Referência ao tipo de parada (Mecânico, Acidente...).',
 'Motivo atrelado à tabela de domínio.', 'conducao', 'conducao'),
('sc_operacao', 'tb_parada_imprevista', 'data_hora_inicio', 'Início da parada.',
 'Cronômetro do tablet / Apontamento manual.', 'conducao', 'conducao'),
('sc_operacao', 'tb_parada_imprevista', 'data_hora_fim', 'Término da parada.',
 'Gera o lead-time real subtraindo data_inicio.', 'conducao', 'conducao'),

('sc_operacao', 'tb_anomalia_embarque', 'id', 'ID da anomalia.', 'Chave.', 'conducao', 'conducao'),
('sc_operacao', 'tb_anomalia_embarque', 'relatorio_id', 'Referência à viagem.', 'Vínculo 1:N.', 'conducao', 'conducao'),
('sc_operacao', 'tb_anomalia_embarque', 'dominio_anomalia_id',
 'Referência ao problema (Ex: Animal sangrando, Gaiola cheia).', 'Itens do checklist.', 'conducao', 'conducao'),
('sc_operacao', 'tb_anomalia_embarque', 'descricao_outros', 'Descritivo caso domínio seja "Outros".',
 'Texto livre condicional.', 'conducao', 'conducao'),

('sc_operacao', 'tb_anomalia_desembarque', 'id', 'ID da anomalia de fim de viagem.', 'Chave.', 'conducao', 'conducao'),
('sc_operacao', 'tb_anomalia_desembarque', 'relatorio_id', 'Referência à viagem.', 'Vínculo 1:N.', 'conducao',
 'conducao'),
('sc_operacao', 'tb_anomalia_desembarque', 'dominio_anomalia_id',
 'Referência ao problema (Ex: Porteira n/ abre, Arraste).', 'Itens do checklist de recepção.', 'conducao', 'conducao'),
('sc_operacao', 'tb_anomalia_desembarque', 'descricao_outros', 'Descritivo caso domínio seja "Outros".',
 'Texto livre condicional.', 'conducao', 'conducao'),

('sc_operacao', 'tb_auditoria_analise', 'id', 'ID da análise interna de auditoria.', 'Chave do Backoffice.',
 'auditoria', 'auditoria'),
('sc_operacao', 'tb_auditoria_analise', 'relatorio_id', 'Relatório submetido a aprovação (Backoffice).', 'Foreign key.',
 'auditoria', 'auditoria'),
('sc_operacao', 'tb_auditoria_analise', 'analista_id', 'Auditor de Planta / Corporativo.',
 'Quem assinou o aceite eletrônico (Aprovação SLA).', 'auditoria', 'auditoria'),
('sc_operacao', 'tb_auditoria_analise', 'data_hora_analise', 'Carimbo de encerramento do processo.',
 'Indicador de tempo de resposta da equipe interna.', 'auditoria', 'auditoria'),
('sc_operacao', 'tb_auditoria_analise', 'aprovado', 'Aceite final para gerar Fatores de BI.',
 'Impede faturamento de viagens fantasmas/erros críticos.', 'auditoria', 'auditoria'),
('sc_operacao', 'tb_auditoria_analise', 'motivo_rejeicao', 'Justificativa estruturada caso reprovado.',
 'Feedback sistêmico.', 'auditoria', 'auditoria'),
('sc_operacao', 'tb_auditoria_analise', 'parecer_tecnico', 'Nota técnica detalhada.', 'Auditoria fiscal futura.',
 'auditoria', 'auditoria');

COMMIT;